export const ONEDRIVE_FOLDERS = {
  CONTRATOS: process.env.ONEDRIVE_FOLDER_CONTRATOS || "",
  SISTEMA_SEAMAR: process.env.ONEDRIVE_FOLDER_SISTEMA_SEAMAR || "",
  DOCUMENTOS: process.env.ONEDRIVE_FOLDER_DOCUMENTOS || "",
  DOCUMENTOS_RESPALDO: process.env.ONEDRIVE_FOLDER_DOCUMENTOS_RESPALDO || "",
  ESTADOS_BANCARIOS: process.env.ONEDRIVE_FOLDER_ESTADOS_BANCARIOS || "",
  VALORIZACIONES: process.env.ONEDRIVE_FOLDER_VALORIZACIONES || "",
  ORDENES_SERVICIO: process.env.ONEDRIVE_FOLDER_ORDENES_SERVICIO || "",
} as const;