export const ONEDRIVE_FOLDERS = {
  CONTRATOS:
    "01JGBJAHCNGNTAGKBEABAJITBXOCBNH5BJ",

  SISTEMA_SEAMAR:
    "01JGBJAHCF5PBYX3LAG5D26BVOZDA6IQDJ",

  DOCUMENTOS:
    "01JGBJAHALC7ZC73JFERDZC3SE3CUYK3IQ",

  DOCUMENTOS_RESPALDO:
    "01JGBJAHCVORARVAPWGJA2DI7W5TBYWLAE",

  ESTADOS_BANCARIOS:
    "01JGBJAHDZERX4BDNFAFH2IQOXAXZRMEVW",

  VALORIZACIONES:
    "01JGBJAHD3OZLGRDXPQJDZO4ZX6YKQ7436",

  ORDENES_SERVICIO:
    "01JGBJAHAKW7674SLFIVA2EA7H2QDXSCDS",
} as const;